# action.yml
name: 'workflow-housekeeper'
description: 'Delete undesired workflow history'
branding:
  icon: 'trash-2'
  color: 'red'
inputs:
  github-token:
    description: 'Token used to login to GitHub'
    required: true
  repo:
    description: 'Repo to housekeep'
    required: false
    default: ${{ github.repository }}
  ignore-branch-workflows:
    description: 'Ignore runs from workflows currently in ./github/workflow'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Run local action
      id: local-action
      run: |
        ${{ github.action_path }}/lib/housekeeper.sh \
        "${{ inputs.github-token }}" \
        "${{ inputs.repo }}" \
        "${{ inputs.ignore-branch-workflows }}"
      shell: bash
