# action.yml
name: 'workflow-housekeeper'
description: 'Delete undesired workflow history'
branding:
  icon: 'trash-2'
  color: 'red'
inputs:
  ignore-branch-workflows:
    description: 'Ignore runs from workflows currently in ./github/workflow'
    required: false
    default: 'false'
outputs:
  housekeeping_output:
    description: 'Output of housekeeping steps'
    value: ${{ steps.local-action.outputs.housekeeping_output }}
runs:
  using: "composite"
  steps:
    - name: Run local action
      id: local-action
      run: |
        ${{ github.action_path }}/lib/housekeeper.sh \
        "${{ github.repository }}" \
        "${{ inputs.ignore-branch-workflows }}"
      shell: bash
