name: Test action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local action
        uses: ./
        id: local-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ignore-branch-workflows: false
          retention-time: '0 weeks'
          retain-run-count: 3
          dry-run: false
      - name: Get outputs
        run: |
          echo "output: ${{ steps.local-action.outputs.housekeeping_output }}"
