name: Test action

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local action
        uses: ./
        id: local-action
